# Обновленный файл конфигурации для развертывания на Render.com
services:
  - type: worker
    name: spotify-telegram-bot
    # Указываем Render, что среду нужно собирать с помощью Docker.
    # Render автоматически найдет файл с именем Dockerfile в вашем репозитории.
    env: docker
    # buildCommand и startCommand больше не нужны,
    # так как они теперь определены внутри Dockerfile.
    plan: free
    # Переменные окружения остаются без изменений.
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false

