services:
  - type: worker
    name: spotify-telegram-bot
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python spotify_downloader_bot.py"a
    buildpacks:
      - heroku/python
      - https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
